### ISSUE TITLE
Version 1.5 Release Checklist

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#1280]
Steps for 1.5 version bump:

- [x] Branch release-1.5
- [x] Do version bump
- [x] Update tests and run tests
- [x] Create change log/release notes
- [x] Review documentation build
- [x] Merge into master
- [x] Push release to PyPI ([instructions](https://bbengfort.github.io/programmer/2016/01/20/packaging-with-pypi.html))
- [x] Create 1.0 tag
 - [x] Copy change log to release notes
- [x] Push documentation to Read the Docs
- [x] Merge release into develop
- [ ] Delete release
- [x] Make issue for updating Zonodo reference
- [x] Make issue for releasing Conda package
- [ ] Announce on Twitter & Reddit!
