### ISSUE TITLE
Use yellowbrick.datasets in tests

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#682]
In #535 we implemented new `Dataset` and `Corpus` datasets. These datasets should replace the current `tests.datasets` to ensure standardization and that our examples work.

Subtasks:

- [x] Rename tests.fixtures.TestDataset to tests.fixtures.Dataset (prefix warnings in runner) 
- [x] Remove `tests/datasets.py`
- [x] Remove all `DatasetMixin` extensions
- [x] ~Create fixtures for synthetic datasets~ (moved to #910)
- [x] Replace `self.load_concrete` with `yellowbrick.datasets.load_concrete`, etc. 
- [x] Remove `dataset.py` and `DatasetMixin` classes
- [ ] In numpy structured array tests use `Dataset.to_numpy` 
- [ ] in pandas tests use `Dataset.to_pandas` 
- [x] ~Update tests to use `windows_tol` instead of conditional tolerances~ (moved to #911)
- [x] ~update contributor guide with use of datasets/fixtures in tests (both random and real)~ (moved to #441)

This task will likely affect/touch _most_ of our tests. I expect that many baseline images will also have to be replaced because the datasets may not be exactly the same.

There has been some question about the use of PyTest fixtures (which are currently primarily used for the randomly generated test data sets) to protect our tests from modifications to the data. This adds a little bit more complication to the test suite but protects us from future changes. Throughout this PR we should inspect our use of data and fixtures and determine a consistent method for using both randomly generated data and yellowbrick datasets. Then add this methodology to the contributor documentation.

This also might be future-proofing against future PyTest releases (#714). 

See #746 and #735 

**UPDATE**: Based on some of our discussions we feel that datasets in tests should be _read only_. The scenario we imagined where datasets might be modified is to "corrupt" them to add missing values or lower their F1 score for the purposes of better tests. In this case, however, we should create a new dataset in the dataset module or use a randomly generated dataset. Note also that Yellowbrick visualizers that are transformers should also not modify the data but should create a new arrray to return.
